LCOccasionMessageTable:
  Type: AWS::DynamoDB::Table
  Properties:
    AttributeDefinitions:
      - AttributeName: occasionName
        AttributeType: S
      - AttributeName: isHost
        AttributeType: S  
      - AttributeName: createdAt
        AttributeType: S               
    KeySchema:
      - AttributeName: occasionName
        KeyType: HASH
      - AttributeName: createdAt
        KeyType: RANGE        
    BillingMode: PAY_PER_REQUEST
    GlobalSecondaryIndexes:
      - IndexName: occasionName-isHost-Index
        KeySchema:
          - AttributeName: occasionName
            KeyType: HASH
          - AttributeName: isHost
            KeyType: RANGE
        Projection:
          ProjectionType: "ALL"  
    TableName: ${self:provider.environment.LC_OCCASION_MESSAGE_TABLE}
