service: admin-voucher-service
useDotenv: true
frameworkVersion: "3"

plugins:
  - serverless-bundle
  - serverless-domain-manager
provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.region.${sls:stage}}

  environment:
    VOUCHER_TABLE_NAME: VoucherTable-${sls:stage}
    PENDING_VOUCHER_TIME: ${self:custom.pendingVoucherTime.${sls:stage}}
    # S3_BUCKET_NAME: ${self:custom.s3BucketName.${sls:stage}}

  iam:
    role:
      statements:
        - ${file(iam/VoucherTableIAM.yml):VoucherTableIAM}

resources:
  Resources:
    VoucherTable: ${file(resources/VoucherTable.yml):VoucherTable}

functions:
  createVoucher:
    handler: src/handlers/createVoucher.handler
    events:
      - http:
          method: POST
          path: /create
          cors: true
  updateVoucher:
    handler: src/handlers/updateVoucher.handler
    events:
      - http:
          method: PATCH
          path: /update
          cors: true
  voucherList:
    handler: src/handlers/vouchersList.handler
    events:
      - http:
          method: GET
          path: /list
          cors: true
  getVoucher:
    handler: src/handlers/getVoucher.handler
    events:
      - http:
          method: GET
          path: /get
          cors: true
  getVoucherById:
    handler: src/handlers/getVoucherByVoucherId.handler
    events:
      - http:
          method: GET
          path: /getById
          cors: true
  processPendingVouchers:
    handler: src/handlers/processPendingVouchers.handler
    events:
      - schedule: rate(${self:custom.cronTime.${sls:stage}})
  bulkUpdate:
    handler: src/handlers/bulkUpdate.handler
    timeout: 30
    events:
      - http:
          method: PATCh
          path: /bulkUpdate
          cors: true
custom:
  VoucherTableName: VoucherTable-${sls:stage}

  domains:
    dev: dev.sagoonlite.com
    testing: testing.sagoon.com
    staging: staging.sagoon.com
    prod: prod.sagoon.com

  region:
    dev: eu-central-1
    testing: ap-southeast-1
    staging: ap-southeast-1
    prod: ap-south-1

  pendingVoucherTime:
    dev: 90
    staging: 90
    prod: 5

  cronTime:
    dev: 3 hours
    staging: 3 hours
    prod: 5 minutes

  accessControlAllowOrigin:
    dev: "*"
    testing: "*"
    staging: "*.sagoon.com"
    prod: "*.sagoon.com"

  customDomain:
    domainName: ${self:custom.domains.${sls:stage}}
    certificateName: ${self:custom.domains.${sls:stage}}
    basePath: adminVoucher
    stage: ${sls:stage}
    createRoute53Record: true
    endpointType: edge
