service: admin-connection-service
useDotenv: true
frameworkVersion: "3"

plugins:
  - serverless-bundle
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.region.${sls:stage}}

  environment:
    # ACCESS_KEY_ID: ${env:ACCESS_KEY_ID}
    # SECRET_ACCESS_KEY: ${env:SECRET_ACCESS_KEY}
    REGION: ${self:provider.region}
    CONNECTION_STATS_TABLE_NAME: ConnectionStatsTable-${sls:stage}
    ACCESS_CONTROL_ALLOW_ORIGIN: ${self.custom.accessControlAllowOrigin.${sls:stage}}

  iam:
    role:
      statements:
        - ${file(iam/connectionStatsTableIAM.yml):ConnectionStatsTable}
        - ${file(iam/InvokeLambdaIAM.yml):InvokeLambdaIAM}

functions:
  getStats:
    handler: src/handlers/getStats.handler
    timeout: 30
    events:
      - http:
          method: GET
          path: /connectionStats
          cors: true

custom:
  ConnectionStatsTableName : ConnectionStatsTable-${sls:stage}

  domains:
    dev: dev.sagoonlite.com
    testing: testing.sagoon.com
    staging: staging.sagoon.com
    prod: prod.sagoon.com

  region:
    dev: eu-central-1
    testing: ap-southeast-1
    staging: ap-southeast-1
    prod: ap-south-1

  customDomain:
    domainName: ${self:custom.domains.${sls:stage}}
    certificateName: ${self:custom.domains.${sls:stage}}
    basePath: connectionAdmin
    stage: ${sls:stage}
    createRoute53Record: true
    endpointType: edge
