InstagramOrdersTable:
  Type: AWS::DynamoDB::Table
  DeletionPolicy: Retain
  Properties:
    TableName: ${self:provider.environment.INSTAGRAM_ORDERS_TABLE}
    BillingMode: PAY_PER_REQUEST

    AttributeDefinitions:
      - AttributeName: dialCode
        AttributeType: S
      - AttributeName: createdAt
        AttributeType: S
      - AttributeName: createdDate
        AttributeType: S
      - AttributeName: transactionId
        AttributeType: S
      
    KeySchema:
      - AttributeName: dialCode
        KeyType: HASH
      - AttributeName: createdAt
        KeyType: RANGE

    LocalSecondaryIndexes:
      - IndexName: DialCode-CreatedDate-index
        KeySchema:
          - AttributeName: dialCode
            KeyType: HASH
          - AttributeName: createdDate
            KeyType: RANGE
        Projection:
          ProjectionType: ALL

      - IndexName: DialCode-TransactionId-index
        KeySchema:
          - AttributeName: dialCode
            KeyType: HASH
          - AttributeName: transactionId
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
    GlobalSecondaryIndexes:
      - IndexName: TransactionId-index
        KeySchema:
          - AttributeName: transactionId
            KeyType: HASH
        Projection:
          ProjectionType: ALL
