service: admin-occasion-service
frameworkVersion: "3"

plugins:
  - serverless-bundle
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.region.${sls:stage}}
  environment:
    OCCASION_ICON_TABLE: ${self:custom.OccasionIconTable}
    OCCASION_TEMPLATES_TABLE: ${self:custom.OccasionTemplatesTable}
    OCCASION_CARD_TABLE: ${self:custom.OccasionCardTable}
    S3BUCKET_REGION: ${self:custom.S3BucketRegion}
    OCCASION_ICON_FOLDER: ${self:custom.S3Bucket}/occasion-icons
  iam:
    role:
      statements:
        - ${file(iam/OccasionCardIAM.yml):OccasionCardIAM}
        - ${file(iam/OccasionIconIAM.yml):OccasionIconIAM}
        - ${file(iam/OccasionTemplatesIAM.yml):OccasionTemplatesIAM}
        - ${file(iam/UploadImageIAM.yml):UploadImageIAM}
resources:
  Resources:
    OccasionCardTable: ${file(resources/OccasionCardTable.yml):OccasionCardTable}
    OccasionIconTable: ${file(resources/OccasionIconTable.yml):OccasionIconTable}
    OccasionTemplatesTable: ${file(resources/OccasionTemplatesTable.yml):OccasionTemplatesTable}

functions:
  createOccasionCard:
    handler: src/handlers/CreateOccasionCard.handler
    events:
      - http:
          method: POST
          path: /create-card
          cors: true
  deleteOccasionCard:
    handler: src/handlers/DeleteOccasionCard.handler
    events:
      - http:
          method: DELETE
          path: /delete-card
          cors: true
  getOccasionCard:
    handler: src/handlers/GetOccasionCard.handler
    events:
      - http:
          method: GET
          path: /card/{cardGroup}/{cardName}
          cors: true
  getOccasionCards:
    handler: src/handlers/GetOccasionCards.handler
    events:
      - http:
          method: GET
          path: /cards/{occasionName}
          cors: true
  getOccasions:
    handler: src/handlers/GetOccasions.handler
    events:
      - http:
          method: GET
          path: /occasion
          cors: true
  AddOccasion:
    handler: src/handlers/AddOccasion.handler
    events:
      - http:
          method: PATCH
          path: /occasion
          cors: true
  GetOccasionByName:
    handler: src/handlers/GetOccasionByName.handler
    events:
      - http:
          method: GET
          path: /occasion/{occasionName}
          cors: true
  DeleteOccasion:
    handler: src/handlers/DeleteOccasion.handler
    events:
      - http:
          method: DELETE
          path: /occasion/{occasionName}
          cors: true
  getTemplates:
    handler: src/handlers/GetTemplates.handler
    events:
      - http:
          method: GET
          path: /templates
          cors: true
  addTemplate:
    handler: src/handlers/AddTemplate.handler
    events:
      - http:
          method: POST
          path: /template
          cors: true
  getTemplateByName:
    handler: src/handlers/GetTemplateByName.handler
    events:
      - http:
          method: GET
          path: /template/{occasionName}/{templateName}
          cors: true
  deleteTemplate:
    handler: src/handlers/DeleteTemplate.handler
    events:
      - http:
          method: DELETE
          path: /template/{occasionName}/{templateName}
          cors: true
  getTemplatesByOccasion:
    handler: src/handlers/GetTemplatesByOccasion.handler
    events:
      - http:
          method: GET
          path: /templates/{templateName}
          cors: true
custom:
  OccasionIconTable: "OccasionIconTable-${sls:stage}"
  OccasionTemplatesTable: "OccasionTemplatesTable-${sls:stage}"
  OccasionCardTable: "OccasionCardsTable-${sls:stage}"
  S3Bucket: "sagoon-2022-dev"
  S3BucketRegion: "eu-central-1"

  domains:
    dev: dev.sagoonlite.com
    testing: testing.sagoonlite.com
    staging: staging.sagoon.com
    prod: api.sagoon.com

  region:
    dev: eu-central-1
    testing: ap-southeast-1
    staging: ap-south-1
    prod: ap-south-1

  customDomain:
    domainName: ${self:custom.domains.${sls:stage}}
    certificateName: ${self:custom.domains.${sls:stage}}
    basePath: "admin"
    stage: ${sls:stage}
    createRoute53Record: true
    endpointType: "edge"
