service: admin-appuser-service
useDotenv: true
frameworkVersion: "3"

plugins:
  - serverless-bundle
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.region.${sls:stage}}
  layers:
    - arn:aws:lambda:${aws:region}:${aws:accountId}:layer:common-middleware-layer:${self:custom.commonMiddlewareLayerVersion.${sls:stage}}

  environment:
    REGION: ${self:provider.region}
    APPUSER_TABLE_NAME: UserTable-${sls:stage}
    TRANSACTION_TABLE_NAME: TransactionsTable-${sls:stage}
    USER_REWARDS_TABLE_NAME: UserRewardsTable-${sls:stage}
    ACCESS_CONTROL_ALLOW_ORIGIN: ${self:custom.accessControlAllowOrigin.${sls:stage}}
    CONNECTION_TABLE_NAME: ConnectionTable-${sls:stage}

  iam:
    role:
      statements:
        - ${file(iam/AppUserTableIAM.yml):AppUserTableIAM}
        - ${file(iam/TransactionsTableIAM.yml):TransactionsTableIAM}
        - ${file(iam/UserRewardsTableIAM.yml):UserRewardsTableIAM}
        - ${file(iam/ConnectionsTableIAM.yml):ConnectionsTableIAM}

functions:
  getAppUser:
    handler: src/handlers/getAppUser.handler
    events:
      - http:
          method: GET
          path: /user
          cors: true
  listAppUsers:
    handler: src/handlers/listAppUsers.handler
    events:
      - http:
          method: GET
          path: /users
          cors: true
  getTransactionsByAppUserId:
    handler: src/handlers/getTransactionsByAppUserId.handler
    events:
      - http:
          method: GET
          path: /transactions
          cors: true
  getRewardsByAppUserId:
    handler: src/handlers/getRewardsByAppUserId.handler
    events:
      - http:
          method: GET
          path: /rewards
          cors: true
  getConnectionsByAppUserId:
    handler: src/handlers/getConnectionsByAppUserId.handler
    events:
      - http:
          method: GET
          path: /connections
          cors: true

custom:
  # AppUserTableName: UserTable-${sls:stage}
  # TransactionsTableName: TransactionsTable-${sls:stage}
  # UserRewardsTableNAME: UserRewardsTable-${sls:stage}
  # ConnectionTableName: ConnectionTable-${sls:stage}

  commonMiddlewareLayerVersion:
    dev: 9
    staging: 1
    prod: 1

  domains:
    dev: dev.sagoonlite.com
    testing: testing.sagoon.com
    staging: staging.sagoon.com
    prod: prod.sagoon.com

  region:
    dev: eu-central-1
    testing: ap-southeast-1
    staging: ap-southeast-1
    prod: ap-south-1

  accessControlAllowOrigin:
    dev: "*"
    testing: "*"
    staging: "*"
    prod: "*"

  customDomain:
    domainName: ${self:custom.domains.${sls:stage}}
    certificateName: ${self:custom.domains.${sls:stage}}
    basePath: appUser
    stage: ${sls:stage}
    createRoute53Record: true
    endpointType: edge

    bundle:
      forceExclude: ["common-middleware-layer"]
