NotificationTemplateTable:
  Type: AWS::DynamoDB::Table
  DeletionPolicy: Retain
  Properties:
    AttributeDefinitions:
      - AttributeName: notificationName
        AttributeType: S
    KeySchema:
      - AttributeName: notificationName
        KeyType: HASH
    BillingMode: PAY_PER_REQUEST
    TableName: ${self:custom.NotificationTemplateTable}
