VoucherTable:
  Type: AWS::DynamoDB::Table
  DeletionPolicy: Retain
  Properties:
    AttributeDefinitions:
      - AttributeName: pk
        AttributeType: S
      - AttributeName: status
        AttributeType: S
      - AttributeName: couponVoucherId
        AttributeType: S
      - AttributeName: productName
        AttributeType: S
      - AttributeName: validTill
        AttributeType: N
    KeySchema:
      - AttributeName: pk
        KeyType: HASH
      - AttributeName: couponVoucherId
        KeyType: RANGE
    LocalSecondaryIndexes:
      - IndexName: item_status-Index
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: status
            KeyType: RANGE
        Projection:
          ProjectionType: "ALL"
      - IndexName: item_validTill-Index
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: validTill
            KeyType: RANGE
        Projection:
          ProjectionType: "ALL"
    GlobalSecondaryIndexes:
      - IndexName: couponVoucherId-Index
        KeySchema:
          - AttributeName: couponVoucherId
            KeyType: HASH
        Projection:
          ProjectionType: "ALL"
      - IndexName: productName-Index
        KeySchema:
          - AttributeName: productName
            KeyType: HASH
        Projection:
          ProjectionType: "ALL"
      - IndexName: pk_status-Index
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: status
            KeyType: RANGE
        Projection:
          ProjectionType: "ALL"
    BillingMode: PAY_PER_REQUEST
    TableName: ${self:custom.VoucherTableName}
