service: admin-shop-service
useDotenv: true
frameworkVersion: "3"

plugins:
  - serverless-bundle
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.region.${sls:stage}}

  environment:
    # ACCESS_KEY_ID: ${env:ACCESS_KEY_ID}
    # SECRET_ACCESS_KEY: ${env:SECRET_ACCESS_KEY}
    REGION: ${self:provider.region}
    TRANSACTION_TABLE_NAME: TransactionsTable-${sls:stage}
    USER_TABLE_NAME: UserTable-${sls:stage}
    ACCESS_CONTROL_ALLOW_ORIGIN: ${self.custom.accessControlAllowOrigin.${sls:stage}}

  iam:
    role:
      statements:
        - ${file(iam/UserTableIAM.yml):UserTableIAM}
        - ${file(iam/TransactionsTableIAM.yml):TransactionsTableIAM}
        - ${file(iam/InvokeLambdaIAM.yml):InvokeLambdaIAM}

functions:
  getTransactionsByDate:
    handler: src/handlers/getTransactionsByDate.handler
    events:
      - http:
          method: GET
          path: /transaction/getByDate
          cors: true
  getTransactionsOfUser:
    handler: src/handlers/getTransactionsOfUser.handler
    events:
      - http:
          method: GET
          path: /transaction/byUserId
          cors: true
  getTransactionsByStatus:
    handler: src/handlers/getTransactionsByStatus.handler
    events:
      - http:
          method: GET
          path: /transaction/byStatus
          cors: true
  getTransactionsByTransactionId:
    handler: src/handlers/getTransactionsById.handler
    events:
      - http:
          method: GET
          path: /transaction/transactionId
          cors: true
custom:
  TransactionsTableName: TransactionsTable-${sls:stage}
  UserTableName: UserTable-${sls:stage}

  domains:
    dev: dev.sagoonlite.com
    testing: testing.sagoon.com
    staging: staging.sagoon.com
    prod: prod.sagoon.com

  region:
    dev: eu-central-1
    testing: ap-southeast-1
    staging: ap-southeast-1
    prod: ap-south-1
  accessControlAllowOrigin:
    dev: "*"
    testing: "*"
    staging: "*.sagoon.com"
    prod: "*.sagoon.com"

  customDomain:
    domainName: ${self:custom.domains.${sls:stage}}
    certificateName: ${self:custom.domains.${sls:stage}}
    basePath: shopAdmin
    stage: ${sls:stage}
    createRoute53Record: true
    endpointType: edge
