MessageTable:
  Type: AWS::DynamoDB::Table
  DeletionPolicy: Retain
  Properties:
    AttributeDefinitions:
      - AttributeName: countryCode
        AttributeType: S
      - AttributeName: createdAt
        AttributeType: S               
    KeySchema:
      - AttributeName: countryCode
        KeyType: HASH
      - AttributeName: createdAt
        KeyType: RANGE          
    BillingMode: PAY_PER_REQUEST
    TableName: ${self:custom.MessageTableName}
