service: admin-invitation-service
useDotenv: true
frameworkVersion: "3"

plugins:
  - serverless-bundle
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.region.${sls:stage}}

  environment:
    # ACCESS_KEY_ID: ${env:ACCESS_KEY_ID}
    # SECRET_ACCESS_KEY: ${env:SECRET_ACCESS_KEY}
    REGION: ${self:provider.region}
    INVITATION_TABLE_NAME: InvitationTable-${sls:stage}
    WAITLISTEDUSERS_TABLE_NAME: WaitlistedUsersTable-${sls:stage}
    ACCESS_CONTROL_ALLOW_ORIGIN: ${self.custom.accessControlAllowOrigin.${sls:stage}}

  iam:
    role:
      statements:
        - ${file(iam/InvitationTableIAM.yml):InvitationTableIAM}
        - ${file(iam/WaitlistedUsersIAM.yml):WaitlistedUsersIAM}
        - ${file(iam/InvokeLambdaIAM.yml):InvokeLambdaIAM}

functions:
  createInvitationCode:
    handler: src/handlers/create.handler
    events:
      - http:
          method: POST
          path: /invitation/create
          cors: true
  fetchWaitListedUsers:
    handler: src/handlers/fetchWaitlistedUsers.handler
    events:
      - http:
          method: POST
          path: /fetchWaitListedUsers
          cors: true
custom:
  InvitationTableName: InvitationTable-${sls:stage}

  domains:
    dev: dev.sagoonlite.com
    testing: testing.sagoon.com
    staging: staging.sagoon.com
    prod: prod.sagoon.com

  region:
    dev: eu-central-1
    testing: ap-southeast-1
    staging: ap-southeast-1
    prod: ap-south-1

  customDomain:
    domainName: ${self:custom.domains.${sls:stage}}
    certificateName: ${self:custom.domains.${sls:stage}}
    basePath: invitationAdmin
    stage: ${sls:stage}
    createRoute53Record: true
    endpointType: edge
