FirehosePolicy:
  Type: AWS::IAM::Policy
  Properties:
    PolicyName: "appLaunchFirehoseDeliveryPolicy"
    PolicyDocument: ${file(iam/FirehosePolicyIAM.yml):FirehosePolicyIAM}
    Roles:
      - !Ref FirehoseRole
