FirehosePolicy:
  Type: AWS::IAM::Policy
  Properties:
    PolicyName: "appLaunchFirehoseDeliveryPolicy"
    PolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Action:
            - "s3:AbortMultipartUpload"
            - "s3:GetBucketLocation"
            - "s3:GetObject"
            - "s3:ListBucket"
            - "s3:ListBucketMultipartUploads"
            - "s3:PutObject"
          Resource:
            - !Sub "arn:aws:s3:::userloggedinactivity"
            - !Sub "arn:aws:s3:::userloggedinactivity/*"
    Roles:
      - !Ref FirehoseRole
