UserAppLaunchDeliveryStream:
  Type: AWS::KinesisFirehose::DeliveryStream
  Properties:
    DeliveryStreamName: ${self:service}-${self:provider.stage}-userAppLaunch
    DeliveryStreamType: DirectPut
    S3DestinationConfiguration:
      BucketARN: arn:aws:s3:::userloggedinactivity
      CompressionFormat: UNCOMPRESSED
      RoleARN: !GetAtt FirehoseRole.Arn
